version : '3'

# build contetxt https://stackoverflow.com/questions/50948581/access-to-outside-of-context-in-dockerfile
services : 
  nginx:
    build: 
      context: ./
      dockerfile: ./docker/nginx/DockerFile
    image: registry.gitlab.com/koleda/test-kube-deploy/nginx:1.0.0

  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/DockerFile
    image: registry.gitlab.com/koleda/test-kube-deploy/php-fpm:1.0.0
  
  queue-worker:
    build:
      context: ./
      dockerfile: ./docker/queue-worker/DockerFile
    image: registry.gitlab.com/koleda/test-kube-deploy/queue-worker:1.0.0

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/DockerFile
    image: registry.gitlab.com/koleda/test-kube-deploy/mysql:1.0.0