apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
    environment: development
  name: mysql
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql
      environment: development
  template:
    metadata:
      labels:
        app: mysql
        environment: development
    spec:
      containers:
      - image: registry.gitlab.com/koleda/test-kube-deploy/mysql:1.0.3
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password
        - name: "MYSQL_USER"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: "MYSQL_DATABASE"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_database
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        emptyDir: {}

# kubectl run -n test --image=registry.gitlab.com/koleda/test-kube-deploy/mysql:1.0.3 mysql --port=3306 --env="MYSQL_ROOT_PASSWORD=root" --env="MYSQL_DATABASE=test_db" \ --labels="app=mysql,environment=development"
