# Note that services should be created before deployments
# so that the nodes in the deployment can be properly loadbalanced by the service
# https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: production
  name: laravel-svc
  namespace: {{NAMESPACE}}
spec:
  type: NodePort
  # port ist the port that the service is trying to connect to on the containers in the pod
  # targetPort is the port the service is exposing 
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  externalIPs: 
    - 157.230.61.23
  selector:
    app: laravel
    environment: production