apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
    environment: development
  name: mysql-service
  namspace: test
spec: 
  type: ClusterIP # not node port because we don't want to expose this to the outside world
  ports: 
  - port: 3306
    protocol: TCP
    targetPort: 3306
  - port: 33060
    targetPort: 33060 # for heidi sql