apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
    environment: development
  name: laravel-service-dev
  namespace: test
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 8000 # port open on the service
      nodePort: 31677
      protocol: TCP
      targetPort: 80 # port open on the pod
  selector:
    app: test-app
    environment: development
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost