apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
  namespace: test
  labels:
    app: test-app
data:
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: 'base64:QKy4eujZC1zuwOF19wIh7TeuffMBlwemry7u2iP02xQ='
  APP_DEBUG: 'true'
  APP_URL: http://localhost
  LOG_CHANNEL: stack

  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: '3306'
  DB_DATABASE: test_db
  DB_USERNAME: test_user
  DB_PASSWORD: password

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: '120'

  REDIS_HOST: redis
  REDIS_PASSWORD: ''
  REDIS_PORT: '6379'

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: '2525'
  MAIL_USERNAME: ''
  MAIL_PASSWORD: ''
  MAIL_ENCRYPTION: ''