# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laravel-deployment # each pod will be named this plus a hash
  namespace: test
  labels:
    app: test-app
    environment: production
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    # these are the labels that a service will match when directing traffic to these pods
    matchLabels:
      app: test-app
      environment: production
  # the pod template
  template:
    metadata:
      # all pods created from this deployment will have these labels
      labels:
        app: test-app
        environment: production
    spec:
      imagePullSecrets:
      - name: gitlab-registry-key
      containers:
      - image: registry.gitlab.com/koleda/test-kube-deploy/nginx:1.0.1
        name: nginx
        imagePullPolicy: Always
        #open port 80 on the container for traffic
        ports:
          - containerPort: 80
      - image: registry.gitlab.com/koleda/test-kube-deploy/php-fpm:1.0.1
        name: php-fpm
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        # pull all laravel environement variables in 
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables
        # envFrom:
        # - configMapRef:
        #     name: laravel-env