# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: production
  name: laravel # each pod will be named this plus a hash
  namespace: {{NAMESPACE}}
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: laravel
      environment: production
  template:
    metadata:
      labels:
        app: laravel
        environment: production
    spec:
      imagePullSecrets:
      - name: gitlab-registry-key
      containers:
      - image: registry.gitlab.com/koleda/test-kube-deploy/nginx:1.0.2
        name: nginx
        imagePullPolicy: Always
        #open port 80 on the container for traffic
        ports:
         - containerPort: 80
      - image: registry.gitlab.com/koleda/test-kube-deploy/php-fpm:1.0.2
        name: php-fpm
        imagePullPolicy: Always
        ports:
          - containerPort: 9000