apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: production
  name: mysql
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql
      environment: production
  template:
    metadata:
      labels:
        app: mysql
        environment: production
    spec:
      containers:
      - image: registry.gitlab.com/koleda/test-kube-deploy/mysql:1.0.3
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password
        - name: "MYSQL_USER"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: "MYSQL_DATABASE"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_database
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        emptyDir: {}
        persistentVolumeClaim:
          claimName: 50gi-do-pvc
     