apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: production
  name: mysql
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql
      environment: production
  template:
    metadata:
      labels:
        app: mysql
        environment: production
    spec:
      imagePullSecrets:
      - name: gitlab-registry-key
      containers:
      - image: registry.gitlab.com/koleda/test-kube-deploy/mysql:1.0.3
        imagePullPolicy: Always
        name: mysql
        # New disks come with a lost+found directory that typically kills mysql this passes a flag to the entrypoint script to tell mysql to ignore it
        # See here https://github.com/docker-library/mysql/issues/186 https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_ignore-db-dir
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password
        - name: "MYSQL_USER"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: "MYSQL_DATABASE"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_database
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      # This will ensure these pods have a high affinity for selecting nodes with a label of type=db -- inclusive 
      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      # nodeSelector:
      #   type: db
      # Tolerations allow for tainting a node so that only pods with the specified toleration can be scheduled on it -- exclusive
      # λ kubectl taint nodes node-2 type=db:NoSchedule
      # λ kubectl taint nodes node-2 type- #this removes the taint, it is the same with labels 
      # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations:
      - key: type
        operator: "Equal"
        value: db
        effect: "NoSchedule"
      volumes:  
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: 50gi-do-pvc
     