apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 50gi-do-pvc
  namespace: {{NAMESPACE}}
spec:
  # the volume can only be used by a single node readwriteonce
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: do-block-storage