FROM php:7.2-alpine

LABEL author="Christopher Koleda" version="1.0.0"

RUN apk update && apk --no-cache add shadow && \ 
  docker-php-ext-install pdo pdo_mysql pcntl posix

COPY ./test-app /var/www/html

RUN usermod -u 1001 www-data && \ 
    groupmod -g 1001 www-data && \
    chown -R www-data: /var/www && \ 
    chmod -R 770 /var/www
    
WORKDIR /var/www/html

CMD php artisan queue:work redis --daemon --sleep=3 --tries=3 --timeout=80 --env=production 